config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :meerkat_streams

  root 'welcome#index'

end

app/models/meerkat_stream.rb
class MeerkatStream < ActiveRecord::Base
  has_many :restreams, class_name: "MeerkatStream"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meerkat_streams_controller.rb
class MeerkatStreamsController < ApplicationController
  def index
    @meerkat_streams = MeerkatStream.all
  end

  def show
    @meerkat_stream = MeerkatStream.find(params[:id])
  end

  def new
    @meerkat_stream = MeerkatStream.new
  end

  def edit
    @meerkat_stream = MeerkatStream.find(params[:id])
  end

  def create
    @meerkat_stream = MeerkatStream.new(meerkat_stream_params)

    @meerkat_stream.save
    redirect_to @meerkat_stream
  end

  def update
    @meerkat_stream = MeerkatStream.find(params[:id])

    if @meerkat_stream.update(meerkat_stream_params)
      redirect_to @meerkat_stream
    else
      render 'edit'
    end
  end

  def destroy
    @meerkat_stream = MeerkatStream.find(params[:id])
    @meerkat_stream.destroy

    redirect_to meerkat_streams_path
  end

private
  def meerkat_stream_params
    params.require(:meerkat_stream).permit(:link)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meerkat_streams_helper.rb
module MeerkatStreamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mirrorkat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meerkat_streams/_form.html.erb
<%= form_for @meerkat_stream do |f| %>

    <% if @meerkat_stream.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@meerkat_stream.errors.count, "error") %> prohibited
            this stream from being saved:
          </h2>
          <ul>
            <% @meerkat_stream.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :link %><br>
      <%= f.text_field :link %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/meerkat_streams/edit.html.erb
<h1>Edit stream</h1>

<%= render 'form' %>

<%= link_to 'Back', meerkat_streams_path %>

app/views/meerkat_streams/index.html.erb
<h1>Listing streams</h1>

<%= link_to 'New stream', new_meerkat_stream_path %>

<table>
  <tr>
    <th>Link</th>
    <th colspan="3"></th>
  </tr>

  <% @meerkat_streams.each do |meerkat_stream| %>
      <tr>
        <td><%= meerkat_stream.link %></td>
        <td><%= link_to 'Show', meerkat_stream_path(meerkat_stream) %></td>
        <td><%= link_to 'Edit', edit_meerkat_stream_path(meerkat_stream) %></td>
        <td><%= link_to 'Destroy', meerkat_stream_path(meerkat_stream), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/meerkat_streams/new.html.erb
<h1>New Stream</h1>

<%= render 'form' %>

<%= link_to 'Back', meerkat_streams_path %>

app/views/meerkat_streams/show.html.erb
<p>
  <strong>Link:</strong>
  <%= @meerkat_stream.link %>
</p>

<%= link_to 'Back', meerkat_streams_path %>
<%= link_to 'Edit', edit_meerkat_stream_path(@meerkat_stream) %>

app/views/welcome/index.html.erb
<p></p>
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">MirrorKat</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#parties">MirrorKat Parties</a></li>
        <li><a href="#blotter">The Blotter</a></li>
        <li><a href="#report">Report a stream</a></li>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container theme-showcase" role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Welcome to MirrorKat.com</h1>
    <p>
      Do you enjoy looking at yourself in the mirror? Singing in the shower? Watching Meerkats?
      Farting in your air tight and fashionable SpaceX space suit?
    </p>
    <p>
      You're in the right place.
    </p>
    <p>
      After all, Meerkat is the nerdiest topic since Roko's Basilisk.
    </p>
    <p>This is just the sample home page - work is obviously still in progress.</p>
  </div>

  <div>
    <h2>WTH is MirrorKat</h2>
    <p>
      MirrorKat is a casual effort at providing a catalyst for a global community of Meerkat contributors who make an on going
      and deliberate effort to keep Meerkat a positive, safe, and entertaining experience.
    </p>
    <p>
      Meerkat is an awesome use of technology with the absolute capacity for changing how the world community engages in
      conversation. It is, unfortunately, also the perfect medium for the very worst characteristics of the social internet.
      Among these concerns are child pornography, cyber bullying, pile ons, and demagoguery. (I'm sure there's a ton more).
    </p>
    <p>
      The internet is a big place. If every iPhone user in the world started streaming from a different place at the
      same time, it's quite plausible that you could see any place in the world.
    </p>
    <p>
      Inevitably a subculture of MetaKats will probably emerge to to address these same issues, but for now
      MirrorKat is providing two specific services.
      <ul>
        <li>
          Organizing fun, inclusive, and positive opportunities for parties to collaborate via Meerkat.
        </li>
        <li>
          Provide reputation management and abuse reporting.
        </li>
      </ul>
    </p>
  </div>

  <div>
    <h2>MirrorKat Parties</h2>
    <p>As part of our effort to create benevolent Meerkat interactions we are organizing a number of activities for the
    community. Our first event is scheduled for Wednesday March 25th, 2015 at 6:30 PM PDT. We have several ideas that
    we will test throughout the end of April. Based on the results we will start / stop / continue different activities
    going forward.</p>

    <div>
      <h3>Meerkat Charades Tournament March 25th, 2015 6:30 PM PDT (unix timestamp: 1427333400)</h3>
      <p>Teams of four compete at increasingly difficult charades elimination tournament.</p>
      <p>Teams can register here. Official rules are here.</p>
    </div>
  </div>

  <div>
    <h2>Reputation management</h2>
    <ul>
      <li>
        <div>
          <p>Report abusive, illicit, and other base behaviors here. All reported incidents are disclosed in the MirrorKat
          blotter. For currently running streams that are grossly illegal or in violation of Meerkat's ToS you can provide
          your twitter handle with your report and we will immediately message Meerkat and Twitter to request an immediate take down.
          You may also report a stream anonymously and MirrorKat will reach out to a select group of individuals to connect
          to the allegedly offensive stream to make an effort to validate your report.</p>
        </div>
      </li>
      <li>
        <div>
          <p>Read the blotter.</p>
        </div>
      </li>
      <li>
        <p>
          Help the effort. Click here to become a report jurist.
        </p>
      </li>
    </ul>
  </div>
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/docs.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>